<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        \DB::table("products")->insert([
            ["name"=>"Nike Air Force 1 '07",
            "import_price"=>500000,
            "export_price"=>1200000,
            "discount"=>0.1,
            "color_id"=>1,
            "avatar"=>"air-force-1-07-shoes.png",
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "type_product_id"=>8,
            "design_id"=>null,
            "gender_id"=>3,],

            ["name"=>"Nike Air Force 1 '07",
            "import_price"=>700000,
            "export_price"=>1500000,
            "discount"=>0.15,
            "color_id"=>5,
            "avatar"=>"air-force-1-07-shoes-X.png",
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "type_product_id"=>8,
            "design_id"=>null,
            "gender_id"=>2],


            ["name"=>"Air Jordan 1 Mid SE Craft",
            "import_price"=>800000,
            "export_price"=>1600000,
            "discount"=>0.2,
            "color_id"=>1,
            "design_id"=>2,
            "product_status"=>true,
            "hot_status"=>false,
            "best_seller_status"=>true,
            "avatar"=>"air-jordan-1-mid-se-craft-shoes.png",
            "type_product_id"=>8,
            "gender_id"=>2],

            ["name"=>"Air Jordan 1 Mid SE Craft",
            "import_price"=>900000,
            "export_price"=>1750000,
            "discount"=>0.1,
            "color_id"=>2,
            "design_id"=>3,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"air-jordan-1-mid-se-craft-shoes-X.png",
            "type_product_id"=>5,
            "gender_id"=>2],

            ["name"=>"Air Jordan 1 Elevate High",
            "import_price"=>300000,
            "export_price"=>700000,
            "discount"=>0.2,
            "color_id"=>1,
            "design_id"=>3,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"air-jordan-1-mid-se-shoes.png",
            "type_product_id"=>5,
            "gender_id"=>1],

            ["name"=>"Air Jordan 1 Elevate High",
            "import_price"=>400000,
            "export_price"=>800000,
            "discount"=>0.15,
            "color_id"=>2,
            "design_id"=>3,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"air-jordan-1-mid-se-shoes-X.png",
            "type_product_id"=>5,
            "gender_id"=>2],
            
            ["name"=>"Air Jordan 1 Zoom CMFT 2",
            "import_price"=>300000,
            "export_price"=>7500000,
            "discount"=>0.3,
            "color_id"=>1,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"revolution-6-road-running-shoes.png",
            "type_product_id"=>5,
            "gender_id"=>2],

            ["name"=>"Air Jordan 1 Zoom CMFT 2",
            "import_price"=>400000,
            "export_price"=>900000,
            "discount"=>0.3,
            "color_id"=>5,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"dunk-low-retro-shoes-X.png",
            "type_product_id"=>5,
            "gender_id"=>1],

            ["name"=>"Air Jordan 1 Low SE",
            "import_price"=>700000,
            "export_price"=>1800000,
            "discount"=>0.1,
            "color_id"=>1,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"impact-4-basketball-shoes.png",
            "type_product_id"=>5,
            "gender_id"=>1],

            ["name"=>"Air Jordan 1 Low SE",
            "import_price"=>700000,
            "export_price"=>2000000,
            "discount"=>0.25,
            "color_id"=>2,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"impact-4-basketball-shoes-X.png",
            "type_product_id"=>5,
            "gender_id"=>2],

            // 

            ["name"=>"air jordan-1 low se older shoes",
            "import_price"=>250000,
            "export_price"=>500000,
            "discount"=>0.15,
            "color_id"=>1,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"air-jordan-1-low-se-older-shoes-pwgRgs.png",
            "type_product_id"=>5,
            "gender_id"=>1],

            ["name"=>"air jordan 1 low se shoes",
            "import_price"=>300000,
            "export_price"=>600000,
            "discount"=>0.1,
            "color_id"=>2,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"air-jordan-1-low-se-shoes-fQgpsv-2.png",
            "type_product_id"=>5,
            "gender_id"=>2],

            ["name"=>"air jordan 1 mid shoes",
            "import_price"=>700000,
            "export_price"=>1500000,
            "discount"=>0.3,
            "color_id"=>1,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"air-jordan-1-mid-shoes-SQf7DM.png",
            "type_product_id"=>5,
            "gender_id"=>1],

            ["name"=>"air jordan legacy 312 low shoes",
            "import_price"=>700000,
            "export_price"=>1200000,
            "discount"=>0.3,
            "color_id"=>2,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"air-jordan-legacy-312-low-shoes-9PbsF4.png",
            "type_product_id"=>5,
            "gender_id"=>2],

            ["name"=>"dunk low retro shoes",
            "import_price"=>500000,
            "export_price"=>1100000,
            "discount"=>0.3,
            "color_id"=>1,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"dunk-low-retro-shoes.png",
            "type_product_id"=>5,
            "gender_id"=>1],

            ["name"=>"jordan one take 4 pf shoes",
            "import_price"=>700000,
            "export_price"=>1600000,
            "discount"=>0.3,
            "color_id"=>2,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"jordan-one-take-4-pf-shoes.png",
            "type_product_id"=>5,
            "gender_id"=>2],

            ["name"=>"jordan one take 4 pf shoes-X",
            "import_price"=>700000,
            "export_price"=>1550000,
            "discount"=>0.3,
            "color_id"=>1,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"jordan-one-take-4-pf-shoes-X.png",
            "type_product_id"=>5,
            "gender_id"=>1],

            ["name"=>"revolution 6 road running shoes-X",
            "import_price"=>300000,
            "export_price"=>1000000,
            "discount"=>0.3,
            "color_id"=>2,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"revolution-6-road-running-shoes-X.png",
            "type_product_id"=>1,
            "gender_id"=>2],

            ["name"=>"sabrina 1 ionicep basketball shoes",
            "import_price"=>700000,
            "export_price"=>1500000,
            "discount"=>0.3,
            "color_id"=>1,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"sabrina-1-ionic-ep-basketball-shoes-ZK1Xwv.png",
            "type_product_id"=>4,
            "gender_id"=>1],

            ["name"=>"structure 25 road running shoes",
            "import_price"=>800000,
            "export_price"=>2200000,
            "discount"=>0.3,
            "color_id"=>2,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"structure-25-road-running-shoes-tFBSvw.png",
            "type_product_id"=>1,
            "gender_id"=>1],

            ["name"=>"tech hera shoes",
            "import_price"=>600000,
            "export_price"=>1200000,
            "discount"=>0.3,
            "color_id"=>1,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"tech-hera-shoes.png",
            "type_product_id"=>7,
            "gender_id"=>3],

            ["name"=>"tech hera shoes-X",
            "import_price"=>500000,
            "export_price"=>1000000,
            "discount"=>0.3,
            "color_id"=>2,
            "design_id"=>1,
            "product_status"=>true,
            "hot_status"=>true,
            "best_seller_status"=>true,
            "avatar"=>"tech-hera-shoes-X.png",
            "type_product_id"=>7,
            "gender_id"=>3],
        ]);
    }
}